### ISSUE TITLE
Server 4 and server 2 is down

### ISSUE THREAD

**Issue by Otaku30** [sharn25/Anime-DL#1]
Best server of the app

Server 4 is not responding 

Plzz plzz fix the bug !!

We cannot use too much internet in just 1 episode !!

**Comment by sharn25** [comment]
Fixed in Anime 7.4 release
https://github.com/sharn25/Anime-DL/releases/tag/v7.4

**Comment by Otaku30** [comment]
Thanks i really love your app before but ..
When i got problem i commented !!

Thanks ❣️🔥🔥❣️

Keep up good work !!

**Comment by sharn25** [comment]
Thanks for your support.
You can comment any time. No issue.
It help me keep the app running.
