### ISSUE TITLE
HOW CAN I EXTRACT APK FROM ZIP FILE ?!!

### ISSUE THREAD

**Issue by Otaku30** [sharn25/Anime-DL#2]
Plzz SEND APK OR GIVE SOME HINT FOR EXTRACTING APK FROM THIS ZIP FILE !

**Comment by sharn25** [comment]
Hi,
Please use below link:
https://github.com/sharn25/Anime-DL-Android-Verison/releases/download/v4.0/Anime_DL_Android_v4.0.apk

**Comment by Otaku30** [comment]
THANK YOU SO MUCH BUDDY !!! ❤️❤️❤️🧡❤️❤️

IT'S WORKING!!!


BLESS YOU BRIGHT FUTURE IN SOFTWARE DEPARTMENT !!!
❤️🧡💛❤️💙❤️💙🧡💙💙🧡😍😍💟💟❣️❣️



ON THAT NOTE !!

THANKS AGAIN !

**Comment by Otaku30** [comment]
AND MAKE TELEGRAM GROUP OR CHANNEL !!

SO WE CAN CANTACT YOU !!
AND IT WILL HELP YOU TO IMPROVE APP !!

**Comment by sharn25** [comment]
Thanks
