### ISSUE TITLE
Add a feature to stream in an external player like VLC.

### ISSUE THREAD

**Issue by jeryjs** [sharn25/Anime-DL#4]
As the title says, it would be better if an external video player support (like VLC) was added for the streaming option as the internal video player isnt too comfortable and has too little options. Otherwise, you could instead add an option where we can easily copy the video link and play it in VLC manually.

**Comment by sharn25** [comment]
Thanks for your suggestion. 
Will add in next version.

**Comment by jeryjs** [comment]
I appreciate it, Also, Great App !!!
