### ISSUE TITLE
Assemble error: java.lang.Exception: ffmpeg error

### ISSUE THREAD

**Issue by jeryjs** [sharn25/Anime-DL#5]
When i try to download an anime with server 2, i get this error at the assembling stage (after download finishes) :

"manifest downloaded
ffmpeg exit status: 1
[INFO] MainWindow : Queue stopped
Assemble error: java.lang.Exception: ffmpeg error
[ERROR] WinUtils : java.io.FileNotFoundException
[INFO] MainWindow_removeDownloads : Sucessfully Deleted Temp: C:\Users\Jery Js\.animedl\temp\2171f1b0-75fe-413f-aaf1-b38d4c9bc4f6"

**Comment by sharn25** [comment]
Can you check for ffmpeg libs path in setting

**Comment by jeryjs** [comment]
I extracted the ffmpeg archive to the same location where AnimeDL is located and set the ffmpeg libs path as that location.

![image](https://user-images.githubusercontent.com/77010142/103744976-b9fc8e00-500f-11eb-8a3b-73ca22822993.png)
![image](https://user-images.githubusercontent.com/77010142/103744725-4e1a2580-500f-11eb-89a9-7627824c2d72.png)

So, did i set the wrong location or something?.

**Comment by sharn25** [comment]
Can you share anime name and source I tring. In the meantime can you try moving the ffmpeg files to spearhead folder and linking it in the settings.

**Comment by jeryjs** [comment]
I get the same error for **all** the animes in Source 2. Also, what does **spearhead folder** mean?

**Comment by sharn25** [comment]
Sry, separate folder. And can you share me the logs - all from cmd

**Comment by jeryjs** [comment]
So, I created a separate folder and placed ffmpeg in it and when i set the location, it showed successful. Then i tried downloading a random anime and it still showed error. [Here's](https://justpaste.it/78me4) the log : `https://justpaste.it/78me4`
